### ISSUE TITLE
Issues loading GPT2 model config when using OctupleMono tokenizer

### ISSUE THREAD

**Issue by dubisx** [Natooz/MidiTok#38]
Hello again Natooz,

I've been trying to train a dummy model using the OctupleMono tokenization, but I've been running into issues while initializing a transformers model for the training. It appears that the special tokens(['PAD'],['EOS'],['BOS']) are of NoneType, and they can not be loaded into the config? I'm attaching a colab link so that you can look at the code, since I am not sure where the issue lies, as this worked both with MIDILike and REMI tokenizations. Thankful for any help!

https://colab.research.google.com/gist/dubisx/fd26679c659ecae57ee923804731eb4f/tf-transformer-model-training-dummy.ipynb

**Comment by Natooz** [comment]
Hi there 👋,

As `Octuple` (and `OctupleMono` as well) uses multiple vocabularies, when indexing it to get a token id with `tokenizer['BOS_None']`, you must also give the vocabulary to index (`tokenizer[0, 'BOS_None']`).
For now, you can just replace it with 0 as the special tokens have the same ids across all vocabularies. An update that can handle this special case anyway will be release in the next hours.

Now to use tokenizations with embedding pooling, you must also hack the model so that it can receive multiple tokens at the same time and merge their embeddings. Here are input and output modules that can do it in PyTorch:
(`N` is batch size, `T` sequence length, `E` model dimension, `Z` number of token types, `*` variable)

```Python
class MultiEmbeddings(Module):
    """Multi-input module, taking several tokens as input, converting them to embeddings and
    concatenate them to make a single 'merged' embedding

    :param num_classes: number of classes for each token type
    :param embedding_sizes: sizes of each embedding type
    :param d_model: size of the final embedding, i.e. dimension of the transformer
    :param padding_idx: padding index, must be the same for each token type
    """
    def __init__(self, num_classes: List[int], embedding_sizes: List[int], d_model: int, padding_idx: int = 0):
        assert len(num_classes) == len(embedding_sizes), \
            f'The number of classes and embedding sizes must be the same ({len(num_classes)} and ' \
            f'{len(embedding_sizes)} were given)'
        super().__init__()
        self.embedding_layers = ModuleList([Embedding(num_classes[i], embedding_sizes[i], padding_idx)
                                            for i in range(len(num_classes))])
        self.proj = Linear(sum(embedding_sizes), d_model)

    def forward(self, x) -> Tensor:
        """

        :param x: Tokens sequences, shape: (N,T,Z)
        :return: Embeddings, as a tensor with a shape (N,T,E)
        """
        embeds = []
        for i, mod in enumerate(self.embedding_layers):
            embeds.append(mod(x[:, :, i]))
        x = cat(embeds, dim=-1)  # (N,T,sum(embedding_sizes))
        return self.proj(x)  # (N,T,E)


class MultiOutput(Module):
    """Multi-output module.

    :param num_classes: number of classes for each token type
    :param d_model: size of the final embedding, i.e. dimension of the transformer
    """
    def __init__(self, num_classes: List[int], d_model: int):
        super().__init__()
        self.output_layers = ModuleList([Linear(d_model, num) for num in num_classes])

    def forward(self, x) -> List[Tensor]:
        """

        :param x: Tokens sequences, shape: (N,T,E)
        :return: List of tensors of shape (N,T,*)
        """
        return [out(x) for out in self.output_layers]  # (N,T,*)
```
