### ISSUE TITLE
Latest release documentation not showing properly

### ISSUE THREAD

**Issue by Kapitan11** [Natooz/MidiTok#39]
Hey! 

In the latest release update `v2.0.5`, something caused the [documentation](https://miditok.readthedocs.io/en/latest/) to not show the descriptions at all.

`v2.0.4` release works fine though.

**Comment by Natooz** [comment]
Hey,

Thanks for paying attention to this!
Indeed, the docs did not compile due to an update from readthedocs [causing a dependency issue](https://github.com/readthedocs/readthedocs.org/issues/10290).
Since, a readthedoc config file has been creates to solve this for the next releases. And I just tested for `v2.0.5` (after some updates at readthedocs) and it works now!

**Comment by Kapitan11** [comment]
Thank you for solving the issue on such short notice!
