### ISSUE TITLE
How much "higher" should the vocab be in order to generate the BPE encoding?

### ISSUE THREAD

**Issue by webpolis** [Natooz/MidiTok#44]
Hi

This [code](https://github.com/Natooz/MidiTok/blob/9970ec472bd7d6e983574d5b28d4b8cbcdd82013/miditok/midi_tokenizer.py#L1029) states that the `vocab_size` in `learn_bpe` should be higher than the actual tokenizer's vocab size. It's not clear how much "higher" should it be.

I have processed a bunch of MIDI files using REMIPlus, and saved the corresponding token files.
Then, I used the following code to learn the BPE from the generated tokens set:

```python
    tokenizer.learn_bpe(
        vocab_size=len(tokenizer.vocab),
        tokens_paths=token_files_paths,
        start_from_empty_voc=False,
    )
```

But it just doesn't proceed because of the aforementioned reason. Now I'm trying setting the vocab size arbitrarly:

```python
vocab_size=len(tokenizer.vocab)*1.25,
```

But this fails horribly:

```python
raceback (most recent call last):
  File "/media/nico/data/projects/ai/midigpt/tokenize-midis.py", line 88, in <module>
    tokenizer.learn_bpe(
  File "/home/nico/anaconda3/envs/midigpt/lib/python3.10/site-packages/miditok/midi_tokenizer.py", line 1094, in learn_bpe
    trainer = BpeTrainer(
TypeError: 'float' object cannot be interpreted as an integer
```

Ideally, I'd like to have more info as to how much should I increase it and if that's something MidiTok can handle internally since, IMHO, it seems to be a bit unclear and probably able to be set automatically since the tokenizer has already constructed its internal vocabulary.

**Comment by Natooz** [comment]
Hello,

For the first issue (`vocabulary_size`), I'll shamelessly copy-paste from #43 :)
> In MidiTok, there is a base vocabulary composed of the basic tokens that represent note attributes and time events. These tokens can be seen as the equivalent of characters (or bytes) for natural language.
> A BPE token id (integer, or index of the token in the vocabulary) is linked to a list of bytes, each of these bytes are linked to basic tokens, these basics tokens are used to create the generated notes / MIDI.

Here, the size of the vocabulary after BPE have to be >= to the number of unique non-BPE tokens. By analogy to natural language, if you were to train a tokenizer, you would have to specify a vocabulary size >= to the number of characters that constitute the data. I'll update the documentation so that these notions are clearer.
Now, you might encounter this issue due to a too large base vocabulary. You might need to tune the tokenizer's parameters in order to reduce the number of tokens (eg nb of durations, specific programs ...).

For the second, you simply gave a `float` whereas the trainer requires an `int`. You can fix this by converting it : `int(vocab_size=len(tokenizer.vocab)*1.25)`

**Comment by webpolis** [comment]
It's clearer now! I'll share my work pretty soon.
