### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by asigalov61** [Natooz/MidiTok#5]
Hey Nathan,

Thank you so much for this repo/project. It's absolutely fantastic and much needed!

Europe, and France in particular are unbeatable when it comes to music! I love European sound and tech! :)

Is there any way you can add deltas for all attributes? That would be helpful I think...

Also, things like millisecond timings and easy time manipulation options would also help, even if it is just for 4/4 for now.

Otherwise, thank you again for your great work!

Most sincerely,

Alex

**Comment by asigalov61** [comment]
Another great feature IMHO would be to add tokens to ints/vectors and back so that it can be loaded straight into the dataloader.

PS. Thanks for the follow.

**Comment by Natooz** [comment]
Hi Alex, 
Thank you very much for your compliments and suggestions ! I hope this could be useful !
I love the sounds from all over the world, but have to say that when it comes to electronic music Europe indeed leads the way I think ;) (especially French touch that I love !)

Timings in second units are something that could be implemented for sure ! I didn't do it yet as to me using musical time units makes sense and won't depend on the tempo (unlike seconds), but as some users might prefer it could be done ! Maybe a parameter letting the user the choice between beat or second timings + the appropriate "resolution" would be good. That would imply some work but nothing too difficult.

I am not sure to understand your two other suggestions. By deltas do you mean to represent values (eg pitch) by the relative distances from previous values (intervals ?) ?
And MidiTok generates tokens as Python lists of ints, so that one can convert them into numpy / torch / jax or whatever objects he prefers. For the token -> MIDI conversion, we might allow to use these library objects but that would mean MidiTok would require these libraries installed, so I'm not sure.

Best,

Nathan

**Comment by asigalov61** [comment]
Hey Nathan,

Thank you for your prompt response.

Yes, if you can implement seconds/milliseconds timings that would be helpful because IMHO it makes it easier to mix the tracks if needed.

Yes, I was indeed talking about the differences between current and previous attributes. I.e. delta start times or delta durations or delta pitches. That I think would be useful in terms of compression. I.e. time takes much fewer tokens in delta form than in linear form.

And my other suggestion was to create a ready-to-use wrapper to create a data loader sequence but it is not a big deal.

Regardless, thank you so much for listening to my suggestions. I know that it takes time to implement something like that, so whenever you can do any of it, it will be greatly appreciated.

Code seems to work fine in Jupyter. Just tested it 🙂

Thank you,
Aleksandr


________________________________

**Comment by Natooz** [comment]
Seconds is on the todo list then !

The relative values (or deltas, I don't know how to call this 😄) is something I had in mind and also consider to implement. But I don't see how it would reduce the sequence lengths, maybe you can enlighten me ?
I imagined something like this: the first pitch token is encoded as an absolute value (eg C4), and the following on relative values (eg +5 semitones, -3 semitones ...).

Nathan

**Comment by asigalov61** [comment]
Hey Nathan,

The terminology in the Music AI field is being developed so I think it's ok to call relative stuff deltas for now. At least that is how I call it. I hope you are ok with it...

Yes, deltas would be a simple difference between a current MIDI event and the previous MIDI event.

Now, with time, for example, it helps to reduce token memory consumption/raise the precision of the token.
I.e. In absolute ticks, the time value may take up 2-4 bytes. While delta times would allow us to shrink it into 1 byte, so we can keep all timings in the 1-byte range (0-255).

What I do in my encoding is I do deltas on start-times and then divide it by 10. Then I also take absolute duration and also divide it by 10. This way, both start time and duration fit nicely into 2 bytes (255, 255) for most MIDI compositions.

Does any of it make sense?

Alex
________________________________

**Comment by asigalov61** [comment]
The same would apply to pitches, etc just like you have described it.

This is where sec/ms timings come really handy.
