### ISSUE TITLE
MIDI file Save issue

### ISSUE THREAD

**Issue by ms3744** [Natooz/MidiTok#9]
Hello!

I was using the library to convert some midi files to representations and back again, but I come across this error every time:

> ValueError: message time must be non-negative in MIDI file

The code to recreate this is as follows:
`from miditok import REMIEncoding
import torch

# Creates the tokenizer and list the file paths
remi_enc = REMIEncoding()  # uses defaults parameters in constants.py

# The tokens, let's say produced by your Transformer, 4 tracks of 500 tokens
tokens = torch.randint(low=0, high=len(remi_enc.vocab), size=(4, 500)).tolist()

# The instruments, here piano, violin, french horn and drums
programs = [(0, False), (41, False), (61, False), (0, True)]

# Convert to MIDI and save it
generated_midi = remi_enc.tokens_to_midi(tokens, programs)
generated_midi.dump('file.mid')  # could have been done above by giving the path argument`

How can I fix this asap? The full error is below:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_42/1003010519.py in <module>
     13 # Convert to MIDI and save it
     14 generated_midi = remi_enc.tokens_to_midi(tokens, programs)
---> 15 generated_midi.dump('file.mid')  # could have been done above by giving the path argument

/opt/conda/lib/python3.7/site-packages/miditoolkit/midi/parser.py in dump(self, filename, file, segment, shift, instrument_idx, charset)
    623         if filename:
    624             print(filename)
--> 625             midi_parsed.save(filename=filename)
    626         else:
    627             midi_parsed.save(file=file)

/opt/conda/lib/python3.7/site-packages/mido/midifiles/midifiles.py in save(self, filename, file)
    444         elif filename is not None:
    445             with io.open(filename, 'wb') as file:
--> 446                 self._save(file)
    447         else:
    448             raise ValueError('requires filename or file')

/opt/conda/lib/python3.7/site-packages/mido/midifiles/midifiles.py in _save(self, outfile)
    457 
    458             for track in self.tracks:
--> 459                 write_track(outfile, track)
    460 
    461     def print_tracks(self, meta_only=False):

/opt/conda/lib/python3.7/site-packages/mido/midifiles/midifiles.py in write_track(outfile, track)
    249             raise ValueError('message time must be int in MIDI file')
    250         if msg.time < 0:
--> 251             raise ValueError('message time must be non-negative in MIDI file')
    252 
    253         if msg.is_realtime:

ValueError: message time must be non-negative in MIDI file

**Comment by Natooz** [comment]
Hi Megha !

Thanks for this report !

I assume that you only tried to convert tokens to MIDI with randomly generated tokens like in your code example ? (_tokens = torch.randint(low=0, high=len(remi_enc.vocab), size=(4, 500)).tolist()_)
You should try with real MIDI files, for instance the ones [in the test folder](https://github.com/Natooz/MidiTok/tree/main/tests).

Your bug happens because the generated MIDI contains notes with starting and ending times < 0, which should not happen (as raised by the Mido package). However this can be a consequence with randomly generated tokens. [In the decoding function of Remi](https://github.com/Natooz/MidiTok/blob/main/miditok/remi.py#L146) the first value assigned to the variable counting bars is -1. The REMI representation actually expect the first token to be a **Bar** one, so if a **Position** token comes before this results in notes with negative times for the first bar.

**Comment by Natooz** [comment]
I added a fail-safe for REMI and other tokenizations to handle this case in df1edd16d4c3ca2a258de3a2d03d4d99779c8d72, it will be included in the next version
